#!/usr/bin/env bash

# Copyright (c) 2024 Jordi Marqués
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -eu

source_libs() {
    declare -g progpath
    declare -g progname

    progname="${0##*/}"

    if [[ ! "${0}" == *"/"* ]]; then # path not available (ie: bash script)
        progpath="$(command -v "${0}")"
        progpath="${progpath%/*}"

    elif [[ "${0%/*}" == "" ]]; then # program on root
        progpath="/"
    else
        progpath="${0%/*}" # program not on root
    fi
    # shellcheck disable=SC1091
    . "${progpath}/rmt-lib.sh"
}

show_help() {
    local -i ec
    ec="${1:-0}"
    echo "Usage:"
    echo "    ${progname} leds set <red> <green> <blue>: set leds colours, range 0-255."
    echo
    echo "    ${progname} leds transition <r> <g> <b> <r> <g> <b> <steps> <wait-seconds>:"
    echo "                show a colours transition, from rgb1 to rgb2 in given steps and wait time between two step."
    echo
    echo "    ${progname} gpu get: show current gpu frequency"
    echo
    echo "    ${progname} gpu set <frequency>: set gpu frequency in Mhz"
    echo
    echo "    ${progname} -h|--help: show this help."
    echo
    echo "Examples:"
    echo "    ${progname} leds set 255 0 0"
    echo "    ${progname} leds transition  255 0 0  0 255 0  50 0.02"
    echo "    ${progname} gpu get"
    echo "    ${progname} gpu set 200"
    echo "    ${progname} gpu set 1000"

    exit "${ec}"
}

module_leds() {
    case "${1:-}" in
        "set")
            shift
            [[ "${*}" =~ ^[0-9]+[[:blank:]][0-9]+[[:blank:]][0-9]+$ ]] || show_help 1
            hidraw_leds_set "${@}"
            ;;
        "transition")
            shift
            [[ "${*}" =~ ^([0-9]+[[:blank:]]){7}[.0-9]+$ ]] || show_help 1
            hidraw_leds_transition "${@}"
            ;;
        *)
            show_help 1
            ;;
    esac
}

module_gpu() {
    case "${1:-}" in
        "get")
            shift
            [[ "${#}" -eq 0 ]] || show_help 1
            gpu_frequency_get
            # shellcheck disable=SC2154
            echo "$((__return / 1000000))"
            ;;
        "set")
            shift
            [[ "${*}" =~ ^(200|1000)$ ]] || show_help 1
            gpu_frequency_set "$((${1} * 1000000))"
            ;;
        *)
            show_help 1
            ;;
    esac
}

main() {
    local module

    [[ "${1:-}" =~ ^(-h|--help)$ ]] && show_help 0 || true

    case "${1:-}" in
        "-h" | "--help")
            show_help 0
            ;;
        "leds" | "gpu")
            module="${1}"
            shift
            "module_${module}" "${@}"
            ;;
        *)
            show_help 1
            ;;
    esac
}

source_libs
main "${@}"
